### ISSUE TITLE
pid variable question!

### ISSUE THREAD

**Issue by susLimbaugh** [ltonetwork/uniswap-farming#18]
Hello, I am trying to develop an application in which you can stake an LP of my token, paired with another token for more of my token. Everything seems to be running smoothly, but I am struggling to understand the pid variable. Is each pool marked with a numeric pid as it is added? I have added the LP to the farm via the add function without error and can see I have added an LP in the poolLength call. I have also approved my farm contract to spend my LP token. But when I try to deposit (I have tried both numeric pool id and LP contract address for the pid variable) metamask throws an error when I go to make the transaction. Any help is greatly appreciated!

**Comment by susLimbaugh** [comment]
It almost seems to be an issue with the migration order of LPMock migrating after Farm. When I approve LPMock to Farm, the last test iteration is the one that gets approved, not the current one

**Comment by susLimbaugh** [comment]
Also, does add create a new contract address for users to deposit too, or does it just add the current LP token for users to be able to deposit that specific LP

**Comment by riordant** [comment]
- Pid means "pool id", it is simply an incrementing uint. When you call `add` it automatically adds the next pid for the lp token you are adding.
- it does not create another contract address, there is only one Farm contract. In your UI, you need to specify the pid for the lp toke  that the user selects.
